services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: filestorage
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  file-storing:
    build:
      context: .
      dockerfile: SD3-FileStoringService/Dockerfile
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    volumes:
      - file-uploads:/app/uploads

  file-analysis:
    build:
      context: .
      dockerfile: SD3-FileAnalysisService/Dockerfile
    ports:
      - "8082:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    volumes:
      - analysis-reports:/app/reports

  api-gateway:
    build:
      context: .
      dockerfile: SD3-APIGateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - file-storing
      - file-analysis
volumes:
  pgdata:
  file-uploads:
  analysis-reports: