// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SD3_FileAnalysisService.Infrastructure;

#nullable disable

namespace SD3_FileAnalisysService.Migrations
{
    [DbContext(typeof(FileAnalysisDbContext))]
    [Migration("20251212211231_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SD3_FileAnalysisService.Models.AnalysisReport", b =>
                {
                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPlagiarismDetected")
                        .HasColumnType("boolean");

                    b.Property<int>("PlagiarismPercentage")
                        .HasColumnType("integer");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("WordCloudPath")
                        .HasColumnType("text");

                    b.HasKey("ReportId");

                    b.ToTable("reports", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
